#!/bin/bash

DATE=$(date +%d+%m+%Y | sed 's|+|.|g');
OPTS="$1"

#dirs
DRIVE="${HOME}/pCloudDrive";
NOTES_BACKUPS='notes-backups'
NEW_DIR="${DRIVE}/${NOTES_BACKUPS}/notes-$DATE";
NOTES="${DRIVE}/notes/*";

AVAILABLE_BACKUPS=($( ls -1 "${DRIVE}/${NOTES_BACKUPS}/" \
					| egrep -o notes-[0-9]{2}\\.[0-9]{2}\\.[0-9]{4} \
					| sort -t. -k +3n \
					| sort -t. -k +2n ))

#files
LINE_COUNT_FILE="line_count";
FILES_DIFF="${NEW_DIR}/changes-$DATE"
LAST_BACKUP="${DRIVE}/${NOTES_BACKUPS}/${AVAILABLE_BACKUPS[-1]}"

case "$OPTS" in
		-f|--force)
		FORCE=1;
		;;
		-a|--available)
		for a in ${AVAILABLE_BACKUPS[@]}; do
			printf '%s\n' $a;
		done
		exit;
		;;
		*)
		FORCE=0;
		;;
esac

if [ ! -d "${NEW_DIR}" ]; then
	mkdir -v "${NEW_DIR}";
elif [ $FORCE == 1 ]; then
	LAST_BACKUP="${DRIVE}/notes-backups/${AVAILABLE_BACKUPS[-2]}"
	rm $FILES_DIFF;
else
	printf "Daily Backup already created!\n";
	exit 1;
fi

echo "creating ${LINE_COUNT_FILE}";
touch "${NEW_DIR}/${LINE_COUNT_FILE}-${DATE}";

for i in ${NOTES[@]}; do
	wc -l "$i" >> "${NEW_DIR}/${LINE_COUNT_FILE}-${DATE}";
done

echo "copying files:"
for y in ${NOTES[@]}; do
	#cp -v "$y" "${NEW_DIR}/";
	echo "$y" "${NEW_DIR}/";
done

for u in ${NOTES[@]}; do
	diff "${LAST_BACKUP}/$(basename $u)" "${u}" >> $FILES_DIFF;
	echo "${LAST_BACKUP}/$(basename $u)" "${u}";
done
